name: Docker Aria2c
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-aria2c.yml
      - docker/aria2c/**
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Setup
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Docker Build And Push
        uses: docker/build-push-action@v5
        with:
          context: docker/aria2c
          push: true
          tags: tianxiadys/aria2c:1.37.0,tianxiadys/aria2c:latest
